# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk11
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
     - ruslan.topolskiy@gmail.com
    on_success: never # default: change
    on_failure: always # default: always